server:
  port: 8080
  servlet:
    context-path: /movie-ratings

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  application:
    name: movie-ratings

  datasource:
    url: jdbc:mysql://localhost:3306/movie_ratings?createDatabaseIfNotExist=true
    username: root
    password: 1111

  mail:
    host: smtp.gmail.com
    port: 587
    username: ttien0181@gmail.com
    password: hxqt hvmh bjhu jrmw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org:
    root: INFO
    com.example.movie_ratings: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

  flyway:
    enabled: false
